"""empty message

Revision ID: b30f6c5e3b71
Revises: 
Create Date: 2021-03-11 11:25:17.557100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30f6c5e3b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KeyWord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numFU', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fName', sa.String(length=150), nullable=False),
    sa.Column('lName', sa.String(length=150), nullable=False),
    sa.Column('uName', sa.String(length=150), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('KeyWord')
    # ### end Alembic commands ###
